repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: repolinter

  # A short description of the repository that will show up on GitHub
  description: Fork of the TODO Group repolinter — open source repository linter

  # A URL with more information about the repository
  homepage: https://github.com/damian-buho/repolinter

collaborators:
  - username: damian-buho
    permission: admin
