# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: Apache-2.0

allowBuilds:
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@types/node@26.1.1'

overrides:
  qs: 6.15.2
  js-yaml: 4.2.0
